config/routes.rb
AmicaleVersion3::Application.routes.draw do
  resources :photos, :only => [:index, :show, :new, :create] do
  post 'upload', :on => :collection
end

   root 'welcome#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmicaleVersion3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'webcam' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/new.html.erb
<div id="webcam"></div>
<script type="text/javascript">
  webcam.set_swf_url('/webcam.swf');
  webcam.set_api_url('<%= upload_photos_path %>');
  webcam.set_quality(90);
  webcam.set_shutter_sound(true, '/shutter.mp3');
  webcam.configure( 'camera' );
  $('webcam').innerHTML = webcam.get_html(320, 240);
</script>
<input type="button" value="Take picture" onclick="webcam.snap();" />

app/views/welcome/index.html.erb
<div class="jumbotron text-center">
  <h1>Amicale des Beaudottes</h1>
</div>

<hr width=100%>

<div class="panel panel-default menu1">
  <div class="panel-body text-center">
  	<a><class="btn btn-success"> <%= link_to "Envoyer une photo", new_photo_path %></a>
  </div>
</div>

<hr width=100%>

<div class="panel panel-default menu2">
  <div class="panel-body text-center">
    <button type="button" class="btn btn-warning">Laisser un message vocal</button>
  </div>
</div>